import Foundation

/// Bundled shortcode → emoji table used by [`SlackEmojiParser`]. Curated subset (~150 entries)
/// of the most-used Slack / Discord / GitHub shortcodes — enough to cover everyday chat
/// reactions and common nouns without bloating the binary or shipping the full Unicode list.
///
/// Keys are lowercase ASCII; the parser lowercases captured shortcodes before lookup, so
/// users can type `:Smile:` and still get a match.
public enum SlackEmojiTable {

	/// Reverse lookup from `defaultTable`: returns the canonical shortcode for `emoji`,
	/// or `nil` if no entry maps to it. When multiple shortcodes map to the same emoji
	/// (e.g. `+1` and `thumbsup` both → 👍), the shorter shortcode wins; ties break
	/// alphabetically so the result is deterministic. Backed by a lazily-built cache.
	public static func shortcode(for emoji: String) -> String? {
		defaultReverseLookup[emoji]
	}

	/// Builds a deterministic `emoji → shortcode` map. Shortest shortcode wins; ties
	/// break alphabetically.
	static func reverseLookup(from table: [String: String]) -> [String: String] {
		var result: [String: String] = [:]
		result.reserveCapacity(table.count)
		for (shortcode, emoji) in table {
			if let existing = result[emoji] {
				if shortcode.count < existing.count ||
					(shortcode.count == existing.count && shortcode < existing) {
					result[emoji] = shortcode
				}
			} else {
				result[emoji] = shortcode
			}
		}
		return result
	}

	private static let defaultReverseLookup: [String: String] = reverseLookup(from: defaultTable)

	public static let defaultTable: [String: String] = [
		// Smileys / faces
		"smile":            "😄",
		"smiley":           "😃",
		"grinning":         "😀",
		"grin":             "😁",
		"laughing":         "😆",
		"sweat_smile":      "😅",
		"rofl":             "🤣",
		"joy":              "😂",
		"slightly_smiling_face": "🙂",
		"upside_down_face": "🙃",
		"wink":             "😉",
		"blush":            "😊",
		"innocent":         "😇",
		"smiling_face_with_three_hearts": "🥰",
		"heart_eyes":       "😍",
		"star_struck":      "🤩",
		"kissing_heart":    "😘",
		"kissing":          "😗",
		"yum":              "😋",
		"stuck_out_tongue": "😛",
		"stuck_out_tongue_winking_eye": "😜",
		"zany_face":        "🤪",
		"hugging_face":     "🤗",
		"thinking_face":    "🤔",
		"shushing_face":    "🤫",
		"neutral_face":     "😐",
		"expressionless":   "😑",
		"no_mouth":         "😶",
		"smirk":            "😏",
		"unamused":         "😒",
		"rolling_eyes":     "🙄",
		"grimacing":        "😬",
		"lying_face":       "🤥",
		"relieved":         "😌",
		"pensive":          "😔",
		"sleepy":           "😪",
		"sleeping":         "😴",
		"mask":             "😷",
		"face_with_thermometer": "🤒",
		"face_with_head_bandage": "🤕",
		"nauseated_face":   "🤢",
		"face_vomiting":    "🤮",
		"hot_face":         "🥵",
		"cold_face":        "🥶",
		"woozy_face":       "🥴",
		"dizzy_face":       "😵",
		"exploding_head":   "🤯",
		"cowboy_hat_face":  "🤠",
		"partying_face":    "🥳",
		"sunglasses":       "😎",
		"nerd_face":        "🤓",
		"monocle_face":     "🧐",
		"confused":         "😕",
		"worried":          "😟",
		"slightly_frowning_face": "🙁",
		"open_mouth":       "😮",
		"hushed":           "😯",
		"astonished":       "😲",
		"flushed":          "😳",
		"pleading_face":    "🥺",
		"frowning":         "😦",
		"anguished":        "😧",
		"fearful":          "😨",
		"cold_sweat":       "😰",
		"disappointed_relieved": "😥",
		"cry":              "😢",
		"sob":              "😭",
		"scream":           "😱",
		"confounded":       "😖",
		"persevere":        "😣",
		"disappointed":     "😞",
		"sweat":            "😓",
		"weary":            "😩",
		"tired_face":       "😫",
		"yawning_face":     "🥱",
		"triumph":          "😤",
		"rage":             "😡",
		"angry":            "😠",
		"cursing_face":     "🤬",
		"smiling_imp":      "😈",
		"imp":              "👿",
		"skull":            "💀",
		"skull_and_crossbones": "☠️",
		"poop":             "💩",
		"clown_face":       "🤡",
		"ghost":            "👻",
		"alien":            "👽",
		"space_invader":    "👾",
		"robot_face":       "🤖",
		"jack_o_lantern":   "🎃",

		// Hands / body
		"wave":             "👋",
		"raised_hand":      "✋",
		"ok_hand":          "👌",
		"v":                "✌️",
		"crossed_fingers":  "🤞",
		"metal":            "🤘",
		"point_up":         "☝️",
		"+1":               "👍",
		"thumbsup":         "👍",
		"-1":               "👎",
		"thumbsdown":       "👎",
		"fist":             "✊",
		"facepunch":        "👊",
		"punch":            "👊",
		"clap":             "👏",
		"raised_hands":     "🙌",
		"open_hands":       "👐",
		"handshake":        "🤝",
		"pray":             "🙏",
		"muscle":           "💪",
		"eyes":             "👀",
		"brain":            "🧠",

		// Hearts / symbols
		"heart":            "❤️",
		"orange_heart":     "🧡",
		"yellow_heart":     "💛",
		"green_heart":      "💚",
		"blue_heart":       "💙",
		"purple_heart":     "💜",
		"black_heart":      "🖤",
		"white_heart":      "🤍",
		"broken_heart":     "💔",
		"two_hearts":       "💕",
		"sparkling_heart":  "💖",
		"heartpulse":       "💗",
		"cupid":            "💘",
		"gift_heart":       "💝",
		"100":              "💯",
		"fire":             "🔥",
		"sparkles":         "✨",
		"star":             "⭐",
		"star2":            "🌟",
		"boom":             "💥",
		"zap":              "⚡",
		"sweat_drops":      "💦",
		"dash":             "💨",
		"musical_note":     "🎵",
		"notes":            "🎶",
		"warning":          "⚠️",
		"no_entry":         "⛔",
		"white_check_mark": "✅",
		"x":                "❌",
		"heavy_check_mark": "✔️",
		"question":         "❓",
		"exclamation":      "❗",
		"bangbang":         "‼️",
		"recycle":          "♻️",

		// Nature / animals
		"sun":              "☀️",
		"sunny":            "☀️",
		"cloud":            "☁️",
		"rainbow":          "🌈",
		"snowflake":        "❄️",
		"earth_africa":     "🌍",
		"earth_americas":   "🌎",
		"earth_asia":       "🌏",
		"dog":              "🐶",
		"cat":              "🐱",
		"mouse":            "🐭",
		"hamster":          "🐹",
		"rabbit":           "🐰",
		"fox_face":         "🦊",
		"bear":             "🐻",
		"panda_face":       "🐼",
		"koala":            "🐨",
		"tiger":            "🐯",
		"lion_face":        "🦁",
		"cow":              "🐮",
		"pig":              "🐷",
		"frog":             "🐸",
		"monkey_face":      "🐵",
		"see_no_evil":      "🙈",
		"hear_no_evil":     "🙉",
		"speak_no_evil":    "🙊",
		"unicorn_face":     "🦄",
		"snake":            "🐍",
		"octopus":          "🐙",
		"whale":            "🐳",
		"dolphin":          "🐬",
		"bug":              "🐛",
		"honeybee":         "🐝",
		"butterfly":        "🦋",

		// Food / drink
		"apple":            "🍎",
		"green_apple":      "🍏",
		"banana":           "🍌",
		"watermelon":       "🍉",
		"grapes":           "🍇",
		"strawberry":       "🍓",
		"peach":            "🍑",
		"pineapple":        "🍍",
		"avocado":          "🥑",
		"tomato":           "🍅",
		"eggplant":         "🍆",
		"hot_pepper":       "🌶️",
		"corn":             "🌽",
		"carrot":           "🥕",
		"bread":            "🍞",
		"cheese_wedge":     "🧀",
		"egg":              "🥚",
		"hamburger":        "🍔",
		"fries":            "🍟",
		"pizza":            "🍕",
		"taco":             "🌮",
		"burrito":          "🌯",
		"popcorn":          "🍿",
		"doughnut":         "🍩",
		"cookie":           "🍪",
		"birthday":         "🎂",
		"cake":             "🍰",
		"chocolate_bar":    "🍫",
		"lollipop":         "🍭",
		"coffee":           "☕",
		"tea":              "🍵",
		"beer":             "🍺",
		"beers":            "🍻",
		"wine_glass":       "🍷",
		"cocktail":         "🍸",
		"tropical_drink":   "🍹",
		"champagne":        "🍾",

		// Travel / objects
		"car":              "🚗",
		"taxi":             "🚕",
		"bus":              "🚌",
		"airplane":         "✈️",
		"rocket":           "🚀",
		"ship":             "🚢",
		"bicycle":          "🚲",
		"house":            "🏠",
		"office":           "🏢",
		"school":           "🏫",
		"hospital":         "🏥",
		"church":           "⛪",
		"mountain":         "⛰️",
		"beach_umbrella":   "🏖️",
		"camping":          "🏕️",
		"tada":             "🎉",
		"confetti_ball":    "🎊",
		"balloon":          "🎈",
		"gift":             "🎁",
		"christmas_tree":   "🎄",
		"trophy":           "🏆",
		"medal":            "🏅",
		"first_place_medal": "🥇",
		"second_place_medal": "🥈",
		"third_place_medal": "🥉",
		"soccer":           "⚽",
		"basketball":       "🏀",
		"football":         "🏈",
		"baseball":         "⚾",
		"tennis":           "🎾",

		// Communication / work
		"phone":            "📱",
		"telephone":        "☎️",
		"computer":         "💻",
		"keyboard":         "⌨️",
		"printer":          "🖨️",
		"camera":           "📷",
		"battery":          "🔋",
		"bulb":             "💡",
		"flashlight":       "🔦",
		"book":             "📖",
		"books":            "📚",
		"pencil":           "✏️",
		"memo":             "📝",
		"clipboard":        "📋",
		"calendar":         "📅",
		"chart_with_upwards_trend": "📈",
		"chart_with_downwards_trend": "📉",
		"mag":              "🔍",
		"lock":             "🔒",
		"unlock":           "🔓",
		"key":              "🔑",
		"hammer":           "🔨",
		"wrench":           "🔧",
		"gear":             "⚙️",
		"hourglass":        "⌛",
		"alarm_clock":      "⏰",
		"mailbox":          "📫",
		"envelope":         "✉️",
		"package":          "📦",
		"money_with_wings": "💸",
		"moneybag":         "💰",
		"credit_card":      "💳",
		"gem":              "💎"
	]
}
